spring.application.name=MiniBank
spring.datasource.url=jdbc:postgresql://localhost:5432/minibank
spring.datasource.username=postgres
spring.datasource.password=123123123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true